require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true

Style/Documentation:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/FetchEnvVar:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

# Fixes Country.find_by_common_name warning
Rails/DynamicFindBy:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - db/migrate/**/*.rb
    - lib/utils/**/*_renderer.rb

RSpec/ImplicitExpect:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - lib/utils/**/*_renderer.rb
